# Generated by Django 4.1.7 on 2023-04-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
    ]
